<style type="text/css">
.colorText {
    color: red;
}
table {
    width: 100%;
}
.page_header img {
    width: 35.00mm;
    height: 12.00mm;
}
.page_header td {
    width: 50%;
}
.page_header td.logo {
    text-align: right;
}
.page_header td {
    vertical-align: top;
}

.page_footer {
    text-align: center;
}
div.address {
    margin-bottom: 5mm;
}
table.invoice {
    border-collapse: collapse;
}
table.invoice td, table.invoice th {
    border: 0.2mm solid #848484;
    text-align: right;
    padding: 1mm 3mm;
}
table.invoice td p, table.invoice th p {
    padding: 0 2mm;
}
table.invoice .desc {
    width: 40%;
}
</style>
<page backtop="26mm" backbottom="30mm">
    <page_header class="page_header">
        <table>
            <tr>
                <td>
                    <h6>Domainsabrechnung ip&more GmbH</h6>
                </td>
                <td class="logo">
                    <img src="<?php echo __DIR__; ?>/logo.png">
                </td>
            </tr>
        </table>
    </page_header>
    <page_footer class="page_footer" >
        <hr />
        Weitere Information können Sie über Ihr Kundenportal einsehen.
        <p>Alle Preise verstehen sich zuzüglich 19% MwSt. Es gelten die ABG der ip&more GmbH.</p>
    </page_footer>
    <h4>Summe: <?php echo number_format($this->customers->getTotalPriceFromAll(), 2, ',', ' ') ?> €</h4><br/>
    <?php if (!empty($this->messages)): ?>
        <?php foreach ($this->messages as $i => $m): ?>
            <?php echo $i . '. ' . $m ?><br/>
        <?php endforeach; ?>
    <?php endif ?>
</page>
<?php $i = 1; foreach ($this->customers->getCustomers() as $customer): ?>
<page backtop="26mm" backbottom="30mm" backimg="<?php echo __DIR__; ?>/Unbenannt.png">    
    <page_header class="page_header">
        <table>
            <tr>
                <td>
                    <h6>Domainsabrechnung ip&more GmbH</h6>
                    Beleg: <?php echo $customer->getInvoiceNr() . $i;?><br /> 
                    <h4><?php echo $customer->getName() . ' - ' . $customer->getId();?> </h4>
                </td>
                <td class="logo">
                    <img src="<?php echo __DIR__; ?>/logo.png">
                </td>
            </tr>
        </table>
    </page_header>
    <page_footer class="page_footer" >
        <hr />
        Weitere Information können Sie über Ihr Kundenportal einsehen.
        <p>Alle Preise verstehen sich zuzüglich 19% MwSt. Es gelten die ABG der ip&more GmbH.</p>
        <p>[[page_cu]]/[[page_nb]]</p>
    </page_footer>
    <hr/>
    <table class="invoice">
        <tr style="background-color: #FE9A2E;">
            <th>Domain</th>
            <th>Reg.-Datum</th>
            <th>einmal. Gebühr</th>
            <th>Jahresgebühr</th>
            <th>Summe</th>
        </tr>
        <?php foreach ($customer->getDomains() as $domain): ?>
        <tr>
            <td><?php echo $domain->getName() . ' <span style="font-size: 0.75em;">(' . $domain->getType() . ')</span>'?></td>
            <td><?php echo date('d.m.Y', $domain->getRegDate()) ?> - <?php echo '(' .  date('d.m.Y', $domain->getInvoiceStart()) . ')' ?></td>
            <td><?php echo number_format($domain->getRegPrice(), 2, ',', '') ?> € <?php echo '(' . $domain->getRegFee() . ')' ?></td>
            <td><?php echo number_format($domain->getYearlyPrice(), 2, ',', '') ?> € <?php echo '(' . $domain->getYearlyFee() . ')' ?></td>
            <td><?php echo number_format($domain->getTotalPrice(), 2, ',', '') ?> €</td>
        </tr>
        <?php endforeach; ?>
        <tr style="background-color: #F7D358;">
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Gesamt: <?php echo number_format($customer->getAllDomainPrice(), 2, ',', '')?> €</td>
        </tr>
    </table>
</page>
<?php endforeach; ?>